import { useEffect, useState } from "react";
import { Banknote, Bell, Check, ChevronRight, ClipboardPenLine, CreditCard, MapPin, MessageCircle, Minus, Percent, Plus, QrCode, ReceiptText, ShoppingCart, Truck, X } from "lucide-react";
import { BannerSlide, CartItem, Food, Staff, StaffMessage, StaffNotification, StoreSettings, Transaction, Voucher } from "../../types";
import { FoodCard } from "../FoodCard";
import { ImageWithFallback } from "../figma/ImageWithFallback";
import { MessagesPanel } from "../MessagesPanel";
import { NotificationsPanel } from "../NotificationsPanel";

type OrderType = "Dine In" | "Take Away" | "Delivery";
type PayMethod = "CASH" | "QRIS" | "Online" | "EDC" | "Split";
type ItemDiscount = { mode: "percent" | "nominal"; value: number };
const money = (value: number) => `Rp ${Math.round(value).toLocaleString("id-ID")}`;

interface CashierPOSProps {
  dishes: Food[]; banners: BannerSlide[]; vouchers: Voucher[]; messages: StaffMessage[]; notifications: StaffNotification[]; storeSettings: StoreSettings; currentStaff: Staff | null; loginStaff: (name: string, pin: string) => Promise<void>; sendMessage: (message: Omit<StaffMessage, "id" | "createdAt">) => Promise<void>; favorites: number[]; cart: CartItem[]; toggle: (id: number) => void; add: (food: Food) => void; detail: (food: Food) => void;
  update: (id: number, change: number) => void; clear: () => void; completed: (draft: Omit<Transaction, "id" | "invoice" | "status" | "createdAt">) => Promise<void>;
}

export function CashierPOS({ dishes, banners, vouchers: activeVouchers, messages, notifications, storeSettings, currentStaff, loginStaff, sendMessage, favorites, cart, toggle, add, detail, update, clear, completed }: CashierPOSProps) {
  const [orderType, setOrderType] = useState<OrderType>("Dine In");
  const [payment, setPayment] = useState<PayMethod>("CASH");
  const [table, setTable] = useState(""); const [address, setAddress] = useState(""); const [driver, setDriver] = useState(""); const [customer, setCustomer] = useState("Guest");
  const [received, setReceived] = useState(""); const [reference, setReference] = useState(""); const [notes, setNotes] = useState<Record<number,string>>({}); const [discounts, setDiscounts] = useState<Record<number,ItemDiscount>>({}); const [editingDiscount, setEditingDiscount] = useState<number | null>(null);
  const [voucher, setVoucher] = useState<{ label: string; discount: number } | null>(null); const [showVouchers, setShowVouchers] = useState(false); const [confirm, setConfirm] = useState(false); const [receipt, setReceipt] = useState(false); const [splitCash, setSplitCash] = useState(""); const [splitQris, setSplitQris] = useState("");
  const [finalCart, setFinalCart] = useState<CartItem[]>([]); const [finalSummary, setFinalSummary] = useState({ total: 0, tax: 0, discount: 0, payment: "CASH" as PayMethod, orderType: "Dine In" as OrderType, customer: "Guest", table: "", address: "", driver: "", change: 0 });
  const [sentToKitchen, setSentToKitchen] = useState(false);
  const printReceipt = () => window.print();
  const sendToKDS = () => { if (!cart.length) return; const channel = new BroadcastChannel("bycashier-kds"); channel.postMessage({ type: "order-created", order: { id: crypto.randomUUID(), invoice: `KDS-${Date.now().toString().slice(-6)}`, items: cart.map(row => ({ name: row.food.name, qty: row.qty, note: notes[row.food.id] })), status: "New", createdAt: new Date().toISOString(), cashier: currentStaff?.name || "Kasir" } }); channel.close(); setSentToKitchen(true); };
  const [slide, setSlide] = useState(0);
  const [messagesOpen, setMessagesOpen] = useState(false);
  const [notificationsOpen, setNotificationsOpen] = useState(false);
  const [profileOpen, setProfileOpen] = useState(false);
  useEffect(() => { setSlide(0); }, [banners.length]);
  useEffect(() => { if (banners.length < 2) return; const timer = window.setInterval(() => setSlide(current => (current + 1) % banners.length), 4500); return () => window.clearInterval(timer); }, [banners.length]);
  const subtotal = cart.reduce((total, item) => total + item.food.price * 15000 * item.qty, 0);
  const itemDiscount = cart.reduce((total, item) => { const active = discounts[item.food.id]; const row = item.food.price * 15000 * item.qty; return total + (active ? active.mode === "percent" ? row * active.value / 100 : active.value : 0); }, 0);
  const voucherDiscount = voucher ? Math.min(voucher.discount, Math.max(0, subtotal - itemDiscount)) : 0;
  const afterDiscount = subtotal - itemDiscount - voucherDiscount;
  const tax = Math.round(afterDiscount * (storeSettings.taxRate / 100)); const total = afterDiscount + tax;
  const paid = payment === "Split" ? Number(splitCash || 0) + Number(splitQris || 0) : Number(received || 0);
  const validPayment = payment === "CASH" ? paid >= total : payment === "Split" ? paid === total : true;
  const vouchers = activeVouchers.filter(item => item.active && new Date(item.expiresAt) >= new Date() && subtotal >= item.minimum).map(item => ({ label: item.name, discount: item.type === "percent" ? Math.round(subtotal * item.value / 100) : item.value }));
  const paymentChoices: { id: PayMethod; icon: React.ReactNode }[] = [{ id:"CASH", icon:<Banknote size={17}/> },{ id:"QRIS", icon:<QrCode size={17}/> },{ id:"Online", icon:<CreditCard size={17}/> },{ id:"EDC", icon:<CreditCard size={17}/> },{ id:"Split", icon:<ReceiptText size={17}/> }].filter(choice => storeSettings.paymentMethods[choice.id]);
  const finish = async () => { const summary={ total, tax, discount: itemDiscount + voucherDiscount, payment, orderType, customer, table, address, driver, change: Math.max(0, paid - total) }; setFinalCart(cart); setFinalSummary(summary); await completed({ customer: customer || "Guest", items: cart.map(row=>({ name: row.food.name, qty: row.qty, total: row.food.price * 15000 * row.qty })), total, discount: itemDiscount + voucherDiscount, tax, payment, orderType, cashier: currentStaff?.name || "Kasir belum login" }); setConfirm(false); setReceipt(true); clear(); };
  return <div className="px-5 pb-28 pt-5 lg:px-8 lg:pb-10"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs text-gray-500">{storeSettings.storeName} · {currentStaff?.attendance === "Hadir" ? "Shift aktif" : "Belum check-in"}</p><p className="mt-1 font-['Space_Grotesk'] text-xl font-bold text-[#1c075c]">Kasir POS</p></div><div className="flex items-center gap-2"><button onClick={() => setProfileOpen(true)} className="max-w-28 truncate rounded-2xl bg-[#f0ebff] px-3 py-2.5 text-xs font-bold text-[#1c075c]">{currentStaff?.name || "Login staff"}</button><button onClick={() => setMessagesOpen(true)} aria-label="Pesan internal" className="relative grid size-10 place-items-center rounded-2xl bg-white shadow-sm ring-1 ring-gray-100"><MessageCircle size={18} className="text-gray-600"/>{messages.filter(message => message.sender === "admin").length > 0 && <span className="absolute right-2 top-2 size-2 rounded-full bg-[#ffe51c] ring-2 ring-white"/>}</button><button onClick={() => setNotificationsOpen(true)} aria-label="Notifikasi" className="relative grid size-10 place-items-center rounded-2xl bg-white shadow-sm ring-1 ring-gray-100"><Bell size={18} className="text-gray-600"/>{notifications.length > 0 && <span className="absolute right-2 top-2 size-2 rounded-full bg-[#ffe51c] ring-2 ring-white"/>}</button><div className="relative grid size-10 place-items-center rounded-2xl bg-[#1c075c]"><ShoppingCart size={18} className="text-white"/>{cart.length > 0 && <span className="absolute -right-1 -top-1 grid size-5 place-items-center rounded-full bg-[#ffe51c] text-[10px] font-bold text-[#1c075c]">{cart.reduce((sum,row)=>sum+row.qty,0)}</span>}</div></div></div>{activeVouchers.length > 0 && <button onClick={() => setShowVouchers(true)} className="mb-4 flex w-full items-center justify-between rounded-2xl bg-[#f0ebff] px-4 py-3 text-left text-xs text-[#1c075c] transition hover:bg-[#e5dcfa]"><span><b>Promo baru aktif:</b> {activeVouchers[0].name} siap digunakan di transaksi ini.</span><span className="font-bold">Lihat voucher →</span></button>}<div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px] 2xl:grid-cols-[minmax(0,1fr)_400px]">
    <section><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-medium text-gray-500">Kasir aktif · Outlet Jakarta Selatan</p><h1 className="mt-1 font-['Space_Grotesk'] text-3xl font-bold text-[#1c075c]">Transaksi Baru</h1></div><span className="rounded-full bg-[#f0ebff] px-3 py-2 text-xs font-semibold text-[#6d49a4]">{cart.reduce((sum,row)=>sum+row.qty,0)} item di keranjang</span></div><BannerCarousel banners={banners} index={slide} setIndex={setSlide} fallback={dishes[0]?.image || ""}/><div className="mt-6 grid gap-4 sm:grid-cols-2 2xl:grid-cols-3">{dishes.map(food => <FoodCard key={food.id} food={food} isFav={favorites.includes(food.id)} onFav={() => toggle(food.id)} onAdd={() => add(food)} onDetail={() => detail(food)}/>)}</div></section>
    <aside className="h-fit rounded-3xl bg-white shadow-sm ring-1 ring-gray-100 xl:sticky xl:top-5"><div className="flex items-center justify-between border-b border-gray-100 px-5 py-5"><div className="flex items-center gap-2"><ShoppingCart size={18} className="text-[#1c075c]"/><h2 className="font-['Space_Grotesk'] text-lg font-bold text-[#1c075c]">Keranjang</h2><span className="rounded-full bg-[#ffe51c] px-2 py-0.5 text-[10px] font-bold text-[#1c075c]">{cart.reduce((sum,row)=>sum+row.qty,0)}</span></div>{cart.length > 0 && <button onClick={clear} className="text-xs font-semibold text-[#9e4e4e]">Kosongkan</button>}</div>
      <div className="max-h-[42vh] space-y-4 overflow-y-auto px-5 py-5">{cart.length ? cart.map(row => { const unit = row.food.price * 15000; const discount = discounts[row.food.id]; const rowDiscount = discount ? discount.mode === "percent" ? unit*row.qty*discount.value/100 : discount.value : 0; return <div key={row.food.id} className="border-b border-dashed border-gray-200 pb-4 last:border-0"><div className="flex items-start gap-3"><img src={row.food.image} alt={row.food.name} className="size-11 rounded-xl object-cover"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#1c075c]">{row.food.name}</p><p className="mt-0.5 text-[11px] font-medium text-[#5494b6]">{row.size || "Regular"}</p></div><div className="flex items-center rounded-xl bg-[#f7f5fb] px-1 py-1"><button onClick={() => update(row.food.id,-1)} className="grid size-6 place-items-center text-gray-500"><Minus size={14}/></button><span className="w-6 text-center text-xs font-bold">{row.qty}</span><button onClick={() => update(row.food.id,1)} className="grid size-6 place-items-center text-[#1c075c]"><Plus size={14}/></button><button onClick={() => setEditingDiscount(editingDiscount === row.food.id ? null : row.food.id)} className="ml-1 grid size-6 place-items-center rounded-lg bg-[#ffe6ee] text-[#e65373]"><Percent size={13}/></button></div></div>{editingDiscount === row.food.id && <div className="mt-3 grid grid-cols-[1fr_82px] gap-2"><select value={discount?.mode || "percent"} onChange={event => setDiscounts(current => ({...current,[row.food.id]:{mode:event.target.value as "percent"|"nominal",value:discount?.value||0}}))} className="rounded-xl border border-gray-200 bg-white px-2 text-xs outline-none"><option value="percent">Diskon persen (%)</option><option value="nominal">Diskon nominal</option></select><input type="number" value={discount?.value || ""} onChange={event => setDiscounts(current => ({...current,[row.food.id]:{mode:discount?.mode || "percent",value:Number(event.target.value)}}))} placeholder="0" className="rounded-xl border border-gray-200 px-2 text-xs outline-none"/></div>}<label className="mt-3 flex items-center gap-2 rounded-xl bg-[#faf9fd] px-3 py-2"><ClipboardPenLine size={13} className="text-gray-400"/><input value={notes[row.food.id] || ""} onChange={event => setNotes(current => ({...current,[row.food.id]:event.target.value}))} placeholder="Tambah catatan (cth: Less Ice)" className="w-full bg-transparent text-[11px] italic outline-none placeholder:text-gray-400"/></label><div className="mt-3 flex justify-between text-xs"><span className="text-gray-400">Subtotal{rowDiscount > 0 ? ` · diskon ${money(rowDiscount)}` : ""}</span><span className="font-bold text-[#1c075c]">{money(unit*row.qty-rowDiscount)}</span></div></div>; }) : <div className="py-9 text-center"><ShoppingCart className="mx-auto text-gray-300"/><p className="mt-3 text-sm text-gray-400">Keranjang masih kosong</p></div>}</div>
      <div className="border-t border-gray-100 px-5 py-5"><button onClick={() => setShowVouchers(!showVouchers)} className="flex w-full items-center justify-between rounded-xl border border-dashed border-[#f0a5b5] px-3 py-3 text-xs font-bold text-[#de5070]"><span className="flex items-center gap-2"><Percent size={15}/> Terapkan Voucher</span><ChevronRight size={15}/></button>{showVouchers && <div className="mt-2 space-y-2">{vouchers.length ? vouchers.map(item => <button key={item.label} onClick={() => {setVoucher(item);setShowVouchers(false);}} className={`flex w-full justify-between rounded-xl px-3 py-2 text-left text-xs ${voucher?.label===item.label?"bg-[#f0ebff] text-[#1c075c]":"bg-[#faf9fd] text-gray-600"}`}><span>{item.label}</span><span className="font-bold">{money(item.discount)}</span></button>) : <p className="px-1 py-2 text-xs text-gray-400">Belum ada voucher yang memenuhi syarat transaksi.</p>}</div>}<div className="mt-5 rounded-2xl bg-[#1c075c] p-4 text-white"><div className="space-y-2 text-xs text-white/65"><div className="flex justify-between"><span>Subtotal</span><span>{money(subtotal)}</span></div>{itemDiscount+voucherDiscount > 0 && <div className="flex justify-between text-[#ffe51c]"><span>Diskon</span><span>−{money(itemDiscount+voucherDiscount)}</span></div>}<div className="flex justify-between"><span>Pajak {storeSettings.taxRate}%</span><span>{money(tax)}</span></div></div><div className="mt-3 flex justify-between border-t border-white/15 pt-3"><span className="text-sm font-semibold">Total Akhir</span><span className="font-['Space_Grotesk'] text-xl font-bold text-[#ffe51c]">{money(total)}</span></div></div>
      <p className="mt-5 text-[11px] font-bold tracking-wide text-[#1c075c]">TIPE PESANAN</p><div className="mt-2 grid grid-cols-3 gap-2">{(["Dine In","Take Away","Delivery"] as OrderType[]).map(type => <button key={type} onClick={() => setOrderType(type)} className={`flex flex-col items-center gap-1 rounded-xl border px-2 py-3 text-[11px] font-bold ${orderType===type?"border-[#1c075c] bg-[#f0ebff] text-[#1c075c]":"border-gray-100 text-gray-400"}`}>{type==="Delivery"?<Truck size={17}/>:<MapPin size={17}/>} {type}</button>)}</div>{orderType==="Dine In" && <input value={table} onChange={event=>setTable(event.target.value)} placeholder="Nomor meja (opsional)" className="mt-3 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-xs outline-none"/>}{orderType==="Delivery" && <div className="mt-3 space-y-2"><input value={address} onChange={event=>setAddress(event.target.value)} placeholder="Alamat pengantaran" className="w-full rounded-xl border border-gray-200 px-3 py-2.5 text-xs outline-none"/><input value={driver} onChange={event=>setDriver(event.target.value)} placeholder="Pilih / masukkan driver" className="w-full rounded-xl border border-gray-200 px-3 py-2.5 text-xs outline-none"/></div>}
      <p className="mt-5 text-[11px] font-bold tracking-wide text-[#1c075c]">METODE PEMBAYARAN</p><div className="mt-2 grid grid-cols-3 gap-2">{paymentChoices.map(choice => <button key={choice.id} onClick={() => setPayment(choice.id)} className={`flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl border text-[10px] font-bold ${payment===choice.id?"border-[#1c075c] bg-[#f0ebff] text-[#1c075c]":"border-gray-100 text-gray-400"}`}>{choice.icon}{choice.id}</button>)}</div>{payment==="CASH" && <div className="mt-3"><input type="number" value={received} onChange={event=>setReceived(event.target.value)} placeholder="Uang diterima" className="w-full rounded-xl border border-gray-200 px-3 py-2.5 text-xs outline-none"/>{received && <p className={`mt-2 text-xs font-semibold ${paid>=total?"text-[#39875b]":"text-[#d45a5a]"}`}>{paid>=total?`Kembalian ${money(paid-total)}`:`Kurang ${money(total-paid)}`}</p>}</div>}{["QRIS","Online","EDC"].includes(payment) && <input value={reference} onChange={event=>setReference(event.target.value)} placeholder="Nomor referensi (opsional)" className="mt-3 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-xs outline-none"/>}{payment==="Split" && <div className="mt-3 grid grid-cols-2 gap-2"><input type="number" value={splitCash} onChange={event=>setSplitCash(event.target.value)} placeholder="Nominal cash" className="rounded-xl border border-gray-200 px-3 py-2.5 text-xs outline-none"/><input type="number" value={splitQris} onChange={event=>setSplitQris(event.target.value)} placeholder="Nominal QRIS" className="rounded-xl border border-gray-200 px-3 py-2.5 text-xs outline-none"/><p className={`col-span-2 text-xs ${validPayment?"text-[#39875b]":"text-[#d45a5a]"}`}>{validPayment?"Split payment sesuai total":"Total split harus sama dengan total akhir"}</p></div>}<input value={customer} onChange={event=>setCustomer(event.target.value)} placeholder="Nama pelanggan" className="mt-3 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-xs outline-none"/><button disabled={!cart.length || !validPayment} onClick={() => setConfirm(true)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-[#ffe51c] py-3.5 text-sm font-bold text-[#1c075c] transition hover:brightness-105 disabled:cursor-not-allowed disabled:opacity-45"><Check size={17}/> Proses Bayar</button></div>
    </aside></div><div className="fixed bottom-4 left-4 right-4 z-40 mx-auto max-w-xl rounded-2xl bg-white/95 p-2 shadow-xl ring-1 ring-gray-200 backdrop-blur print:hidden"><button onClick={sendToKDS} disabled={!cart.length} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-[#1c075c] py-4 text-sm font-bold text-white transition hover:bg-[#2d1080] disabled:cursor-not-allowed disabled:opacity-40"><ClipboardPenLine size={18}/>{sentToKitchen ? "KDS terkirim" : "Send to KDS"}</button><div className="mt-2 grid grid-cols-2 gap-2"><button onClick={printReceipt} disabled={!cart.length} className="rounded-2xl border border-gray-200 py-3 text-xs font-bold text-[#1c075c] disabled:cursor-not-allowed disabled:opacity-40">Print to kitchen</button><button onClick={printReceipt} disabled={!cart.length} className="rounded-2xl border border-gray-200 py-3 text-xs font-bold text-[#1c075c] disabled:cursor-not-allowed disabled:opacity-40">Print checker</button></div></div>{confirm && <Confirm total={total} orderType={orderType} payment={payment} onClose={()=>setConfirm(false)} onConfirm={finish}/>} {receipt && <Receipt cart={finalCart} {...finalSummary} storeSettings={storeSettings} staffName={currentStaff?.name || "Kasir belum login"} close={()=>setReceipt(false)}/>} {profileOpen && <StaffLogin close={()=>setProfileOpen(false)} login={loginStaff}/>} {messagesOpen && <MessagesPanel messages={messages} currentUser={{id:currentStaff?.id||"cashier-guest",name:currentStaff?.name||"Kasir",photo:currentStaff?.photo,role:currentStaff?.role==="Supervisor"?"supervisor":"cashier"}} send={sendMessage} close={() => setMessagesOpen(false)}/>} {notificationsOpen && <NotificationsPanel notifications={notifications} close={() => setNotificationsOpen(false)}/>}</div>;
}

function Confirm({total,orderType,payment,onClose,onConfirm}:{total:number;orderType:OrderType;payment:PayMethod;onClose:()=>void;onConfirm:()=>void}) { return <div className="fixed inset-0 z-[100] grid place-items-center bg-[#1c075c]/40 p-4"><div className="w-full max-w-sm rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><h2 className="font-['Space_Grotesk'] text-xl font-bold text-[#1c075c]">Checkout pesanan</h2><button onClick={onClose} aria-label="Tutup checkout"><X size={22}/></button></div><div className="mt-5 space-y-3 rounded-2xl bg-[#faf9fd] p-4 text-sm"><div className="flex justify-between"><span className="text-gray-500">Jenis pesanan</span><b className="text-[#1c075c]">{orderType}</b></div><div className="flex justify-between"><span className="text-gray-500">Metode bayar</span><b className="text-[#1c075c]">{payment}</b></div><div className="flex justify-between border-t border-dashed border-gray-200 pt-3"><span className="font-semibold text-[#1c075c]">Total akhir</span><b className="text-[#1c075c]">{money(total)}</b></div></div><button onClick={onConfirm} className="mt-4 w-full rounded-2xl bg-[#ffe51c] py-4 text-sm font-bold text-[#1c075c]">Bayar & Cetak Nota</button><button onClick={onClose} className="mt-4 w-full text-sm font-bold text-[#b65b68]">Batalkan order</button></div></div> }
function Receipt({cart,total,tax,discount,payment,orderType,customer,table,address,driver,change,storeSettings,staffName,close}:{cart:CartItem[];total:number;tax:number;discount:number;payment:PayMethod;orderType:OrderType;customer:string;table:string;address:string;driver:string;change:number;storeSettings:StoreSettings;staffName:string;close:()=>void}) { return <div className="fixed inset-0 z-[100] grid place-items-center overflow-y-auto bg-[#1c075c]/40 p-4"><div className="my-6 w-full max-w-sm rounded-3xl bg-white p-6 shadow-2xl"><div className="text-center">{storeSettings.logo&&<ImageWithFallback src={storeSettings.logo} alt={`Logo ${storeSettings.storeName}`} className="mx-auto mb-3 h-12 max-w-28 object-contain"/>}<p className="font-['Space_Grotesk'] text-xl font-bold text-[#1c075c]">{storeSettings.storeName}</p><p className="mt-1 text-xs text-gray-400">{storeSettings.address}</p><p className="mt-4 text-[11px] text-gray-500">INV-{Date.now().toString().slice(-8)} · {new Date().toLocaleString("id-ID")}</p></div><div className="mt-5 border-y border-dashed border-gray-300 py-4 text-xs text-gray-600"><p>Kasir: {staffName} · Pelanggan: {customer || "Guest"}</p><p className="mt-1">{orderType}{orderType==="Dine In"&&table?` · Meja ${table}`:""}{orderType==="Delivery"?` · ${address} · Driver: ${driver}`:""}</p></div><div className="mt-4 space-y-2 text-sm">{cart.map(row=><div key={row.food.id} className="flex justify-between gap-3"><span>{row.qty}× {row.food.name}</span><b>{money(row.qty*row.food.price*15000)}</b></div>)}</div><div className="mt-4 space-y-2 border-t border-dashed border-gray-300 pt-4 text-sm"><div className="flex justify-between"><span>Pajak {storeSettings.taxRate}%</span><span>{money(tax)}</span></div><div className="flex justify-between"><span>Diskon voucher/item</span><span>−{money(discount)}</span></div><div className="flex justify-between font-bold text-[#1c075c]"><span>Total</span><span>{money(total)}</span></div><div className="flex justify-between"><span>Bayar · {payment}</span><span>{payment==="CASH"?`Kembali ${money(change)}`:"Berhasil"}</span></div></div><p className="mt-5 text-center text-xs text-gray-400">{storeSettings.receiptFooter}</p><button onClick={()=>window.print()} className="mt-5 w-full rounded-2xl bg-[#ffe51c] py-3 text-sm font-bold text-[#1c075c]">Cetak struk</button><button onClick={close} className="mt-2 w-full rounded-2xl bg-[#1c075c] py-3 text-sm font-bold text-white">Selesai</button></div></div> }
function StaffLogin({close,login}:{close:()=>void;login:(name:string,pin:string)=>Promise<void>}) { const [name,setName]=useState("");const [pin,setPin]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);const submit=async()=>{setLoading(true);setError("");try{await login(name,pin);close();}catch(reason){setError(reason instanceof Error?reason.message:"Login gagal");}finally{setLoading(false);}};return <div className="fixed inset-0 z-[120] grid place-items-center bg-[#1c075c]/40 p-4"><div className="w-full max-w-sm rounded-3xl bg-white p-6 shadow-2xl"><h2 className="font-['Space_Grotesk'] text-xl font-bold text-[#1c075c]">Login staff</h2><p className="mt-1 text-xs text-gray-400">Masuk dengan nama dan PIN yang dibuat admin.</p><div className="mt-5 grid gap-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nama staff" className="rounded-xl border border-gray-200 p-3 text-sm"/><input value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))} inputMode="numeric" placeholder="PIN" className="rounded-xl border border-gray-200 p-3 text-sm"/>{error&&<p className="text-xs text-[#c3525f]">{error}</p>}</div><div className="mt-5 flex gap-2"><button onClick={close} className="flex-1 rounded-xl bg-gray-100 py-3 text-sm font-bold">Batal</button><button disabled={loading||!name||!pin} onClick={submit} className="flex-1 rounded-xl bg-[#ffe51c] py-3 text-sm font-bold text-[#1c075c] disabled:opacity-50">{loading?"Memeriksa...":"Masuk"}</button></div></div></div> }
function BannerCarousel({ banners, index, setIndex, fallback }: { banners: BannerSlide[]; index: number; setIndex: (value: number) => void; fallback: string }) { const banner = banners[index]; const title = banner?.title || "Promo untuk pelanggan setia"; const caption = banner?.caption || "Atur spanduk promosi dari Dashboard"; return <div className="relative mt-6 min-h-44 overflow-hidden rounded-3xl bg-[#1c075c] px-6 py-7 text-white"><div className="relative z-10 max-w-[58%]"><span className="inline-block rounded-full bg-[#ffe51c] px-3 py-1 text-[11px] font-bold text-[#1c075c]">● PROMO OUTLET</span><h2 className="mt-3 font-['Space_Grotesk'] text-2xl font-bold leading-tight">{title}</h2><p className="mt-2 text-sm text-white/70">{caption}</p></div>{(banner?.image || fallback) && <div className="absolute right-0 top-0 h-full w-[48%]"><ImageWithFallback src={banner?.image || fallback} alt={banner?.caption || "Spanduk promosi outlet"} className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#1c075c] via-[#1c075c]/35 to-transparent"/></div>}<div className="absolute bottom-4 left-6 z-10 flex gap-1.5">{Array.from({ length: Math.max(1,banners.length) }).map((_,item) => <button key={item} onClick={() => setIndex(item)} aria-label={`Slide ${item+1}`} className={`h-1.5 rounded-full ${item===index?"w-5 bg-[#ffe51c]":"w-1.5 bg-white/40"}`}/>)}</div></div> }
