import { useState } from "react";
import { ReceiptText } from "lucide-react";
import { Transaction } from "../../types";

const statusStyle = { Processing: "bg-[#fff3cd] text-[#8a6300]", Completed: "bg-[#e7f5ec] text-[#1a6c35]", Cancelled: "bg-[#fde8e8] text-[#b91c1c]" };
type Props = { filter: string; setFilter: (filter: string) => void; transactions: Transaction[] };

export function HistoryPage({ filter, setFilter, transactions }: Props) {
  const [receipt, setReceipt] = useState<Transaction | null>(null);
  const tabs = ["All Orders", "Completed", "Processing", "Cancelled"];
  const visible = transactions.filter(item => filter === "All Orders" || item.status === filter);
  return <div className="px-5 pb-28 pt-5 lg:px-8 lg:pb-10"><div><p className="text-xs text-gray-500">Kasir POS · transaksi langsung</p><h1 className="mt-1 font-['Space_Grotesk'] text-2xl font-bold text-[#1c075c]">Riwayat Transaksi</h1></div><div className="mt-6 flex flex-wrap gap-2">{tabs.map(tab=><button key={tab} onClick={()=>setFilter(tab)} className={`rounded-full px-4 py-2 text-xs font-bold ${filter===tab?"bg-[#1c075c] text-white":"bg-white text-gray-500 ring-1 ring-gray-200"}`}>{tab}</button>)}</div><div className="mt-5 space-y-3">{visible.length?visible.map(order=><article key={order.id} className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-gray-100"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2"><p className="font-bold text-[#1c075c]">{order.invoice}</p><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${statusStyle[order.status]}`}>{order.status}</span></div><p className="mt-1 text-xs text-gray-500">{order.customer} · {order.items.reduce((sum,item)=>sum+item.qty,0)} item · {new Date(order.createdAt).toLocaleString("id-ID")}</p><p className="mt-2 text-sm font-bold text-[#1c075c]">Rp {order.total.toLocaleString("id-ID")}</p></div><button onClick={()=>setReceipt(order)} className="flex items-center gap-2 rounded-xl bg-[#f0ebff] px-4 py-2.5 text-xs font-bold text-[#1c075c]"><ReceiptText size={14}/> Nota customer</button></div></article>):<p className="rounded-3xl bg-white p-8 text-center text-sm text-gray-400 shadow-sm ring-1 ring-gray-100">Belum ada transaksi kasir pada filter ini.</p>}</div>{receipt&&<ReceiptPreview transaction={receipt} close={()=>setReceipt(null)}/>}</div>;
}
function ReceiptPreview({transaction,close}:{transaction:Transaction;close:()=>void}) { return <div className="fixed inset-0 z-[120] grid place-items-center bg-[#1c075c]/40 p-4"><div className="w-full max-w-sm rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="font-['Space_Grotesk'] text-xl font-bold text-[#1c075c]">Nota Customer</p><p className="mt-1 text-xs text-gray-400">{transaction.invoice}</p></div><button onClick={close} className="text-xl text-gray-400">×</button></div><div className="mt-5 border-y border-dashed border-gray-300 py-4 text-xs text-gray-600"><p>Pelanggan: {transaction.customer}</p><p className="mt-1">Kasir: {transaction.cashier} · {transaction.orderType}</p></div><div className="mt-4 space-y-2 text-sm">{transaction.items.map((item,index)=><div key={`${item.name}-${index}`} className="flex justify-between gap-3"><span>{item.qty}× {item.name}</span><b>Rp {item.total.toLocaleString("id-ID")}</b></div>)}</div><div className="mt-4 space-y-2 border-t border-dashed border-gray-300 pt-4 text-sm"><div className="flex justify-between"><span>Diskon</span><span>−Rp {transaction.discount.toLocaleString("id-ID")}</span></div><div className="flex justify-between"><span>Pajak</span><span>Rp {transaction.tax.toLocaleString("id-ID")}</span></div><div className="flex justify-between font-bold text-[#1c075c]"><span>Total · {transaction.payment}</span><span>Rp {transaction.total.toLocaleString("id-ID")}</span></div></div><button onClick={()=>window.print()} className="mt-6 w-full rounded-2xl bg-[#ffe51c] py-3 text-sm font-bold text-[#1c075c]">Cetak nota</button></div></div>; }
