import { useState } from "react";
import { Camera, LogOut, ShieldCheck } from "lucide-react";
import { Staff } from "../../types";
import { ImageWithFallback } from "../figma/ImageWithFallback";

type Props = { staff: Staff; save: (next: Pick<Staff, "name" | "photo">) => Promise<void>; logout: () => void };

export function ProfilePage({ staff, save, logout }: Props) {
  const [name, setName] = useState(staff.name); const [photo, setPhoto] = useState(staff.photo || ""); const [saving, setSaving] = useState(false);
  const upload = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => setPhoto(String(reader.result)); reader.readAsDataURL(file); };
  const submit = async () => { setSaving(true); try { await save({ name, photo }); } finally { setSaving(false); } };
  return <div className="px-5 pb-28 pt-5 lg:px-8 lg:pb-10"><div><p className="text-xs text-gray-500">Akun & keamanan</p><h1 className="mt-1 font-['Space_Grotesk'] text-3xl font-bold text-[#1c075c]">Profil saya</h1></div><section className="mt-6 max-w-2xl rounded-3xl bg-white p-6 shadow-sm ring-1 ring-gray-100"><div className="flex flex-col items-center gap-5 sm:flex-row"><label className="relative grid size-28 cursor-pointer place-items-center overflow-hidden rounded-3xl bg-[#f0ebff] text-3xl"><span className="font-bold text-[#7c5cbf]">{staff.name.slice(0,1).toUpperCase()}</span>{photo&&<ImageWithFallback src={photo} alt={`Foto profil ${name}`} className="absolute inset-0 size-full object-cover"/>}<span className="absolute bottom-1 right-1 grid size-8 place-items-center rounded-xl bg-[#ffe51c] text-[#1c075c]"><Camera size={15}/></span><input type="file" accept="image/*" onChange={event=>upload(event.target.files?.[0])} className="hidden"/></label><div className="text-center sm:text-left"><h2 className="font-['Space_Grotesk'] text-xl font-bold text-[#1c075c]">{staff.name}</h2><p className="mt-1 text-sm text-[#7c5cbf]">{staff.role} · {staff.shift}</p><span className="mt-3 inline-flex items-center gap-2 rounded-full bg-[#e7f5ec] px-3 py-1.5 text-xs font-bold text-[#287347]"><ShieldCheck size={14}/> Akses {staff.role}</span></div></div><div className="mt-7 grid gap-4"><label className="text-xs font-bold text-[#1c075c]">NAMA TAMPIL<input value={name} onChange={event=>setName(event.target.value)} className="mt-2 w-full rounded-xl border border-gray-200 p-3 text-sm font-normal outline-none"/></label><div className="rounded-2xl bg-[#faf9fd] p-4"><p className="text-xs font-bold text-[#1c075c]">HAK AKSES</p><p className="mt-2 text-sm text-gray-500">{staff.permissions.join(" · ") || "Hak akses ditentukan oleh admin."}</p></div></div><div className="mt-6 flex flex-wrap gap-3"><button disabled={saving||!name.trim()} onClick={submit} className="rounded-xl bg-[#ffe51c] px-5 py-3 text-sm font-bold text-[#1c075c] disabled:opacity-50">{saving?"Menyimpan...":"Simpan profil"}</button><button onClick={logout} className="flex items-center gap-2 rounded-xl bg-[#1c075c] px-5 py-3 text-sm font-bold text-white"><LogOut size={16}/> Logout akun</button></div></section></div>;
}

export function AccountLogin({ close, login }: { close: () => void; login: (name: string, pin: string) => Promise<void> }) { const [name,setName]=useState("");const [pin,setPin]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);const submit=async()=>{setLoading(true);setError("");try{await login(name,pin);close();}catch(reason){setError(reason instanceof Error?reason.message:"Login gagal");}finally{setLoading(false);}};return <div className="fixed inset-0 z-[150] grid place-items-center bg-[#1c075c]/40 p-4"><div className="w-full max-w-sm rounded-3xl bg-white p-6 shadow-2xl"><h2 className="font-['Space_Grotesk'] text-xl font-bold text-[#1c075c]">Login akun</h2><p className="mt-1 text-xs text-gray-400">Admin, Manager, Kitchen, Supervisor, dan Kasir masuk dengan nama serta PIN.</p><div className="mt-5 grid gap-3"><input value={name} onChange={event=>setName(event.target.value)} placeholder="Nama akun" className="rounded-xl border border-gray-200 p-3 text-sm"/><input value={pin} onChange={event=>setPin(event.target.value.replace(/\D/g,""))} inputMode="numeric" placeholder="PIN" className="rounded-xl border border-gray-200 p-3 text-sm"/>{error&&<p className="text-xs text-[#c3525f]">{error}</p>}</div><div className="mt-5 flex gap-2"><button onClick={close} className="flex-1 rounded-xl bg-gray-100 py-3 text-sm font-bold text-gray-600">Batal</button><button disabled={!name||!pin||loading} onClick={submit} className="flex-1 rounded-xl bg-[#ffe51c] py-3 text-sm font-bold text-[#1c075c] disabled:opacity-50">{loading?"Memeriksa...":"Login"}</button></div></div></div>; }
